// <auto-generated />
using System;
using DevPulse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevPulse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DevPulseDbContext))]
    [Migration("20260823035219_AddHubstaffIntegration")]
    partial class AddHubstaffIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevPulse.Domain.Entities.AttendanceCorrectionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("RequestedPunchInUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestedPunchOutUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewerComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId", "WorkDate", "Status");

                    b.ToTable("AttendanceCorrectionRequests", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PunchInIsCorrected")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PunchInUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PunchOutIsCorrected")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PunchOutUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId", "WorkDate")
                        .IsUnique();

                    b.ToTable("AttendanceRecords", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.AttendanceSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("BufferEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("BufferStartTime")
                        .HasColumnType("time");

                    b.Property<string>("OfficeTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("WorkEndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("WorkStartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("AttendanceSettings", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.ClickUpAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastValidatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastValidationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId")
                        .IsUnique();

                    b.ToTable("ClickUpAccounts", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.CompanyHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("FromDate", "ToDate");

                    b.ToTable("CompanyHolidays", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ReportingManagerDeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WorkRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("ReportingManagerDeveloperId");

                    b.ToTable("Developers", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.DeveloperClickUpMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClickUpAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClickUpUserId")
                        .HasColumnType("int");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClickUpAccountId", "ClickUpUserId")
                        .IsUnique();

                    b.HasIndex("DeveloperId", "ClickUpAccountId")
                        .IsUnique();

                    b.ToTable("DeveloperClickUpMappings", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.DeveloperHubstaffMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HubstaffOrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HubstaffUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("HubstaffOrganizationId", "DeveloperId")
                        .IsUnique();

                    b.HasIndex("HubstaffOrganizationId", "HubstaffUserId")
                        .IsUnique();

                    b.ToTable("DeveloperHubstaffMappings", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.DeveloperKpiSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AverageCompletionDays")
                        .HasColumnType("float");

                    b.Property<int>("ChildTaskCount")
                        .HasColumnType("int");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("int");

                    b.Property<double>("CompletionRate")
                        .HasColumnType("float");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeveloperName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("InProgressCount")
                        .HasColumnType("int");

                    b.Property<int>("OnTimeCompletedCount")
                        .HasColumnType("int");

                    b.Property<double?>("OnTimeRate")
                        .HasColumnType("float");

                    b.Property<int>("OverdueCount")
                        .HasColumnType("int");

                    b.Property<int>("ProjectCount")
                        .HasColumnType("int");

                    b.Property<Guid>("SyncRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalTasks")
                        .HasColumnType("int");

                    b.Property<int>("WorkspaceCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("SyncRunId");

                    b.HasIndex("FromDate", "ToDate", "DeveloperId");

                    b.ToTable("DeveloperKpiSnapshots", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.HubstaffDailyActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BillableSeconds")
                        .HasColumnType("int");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("HubstaffDailyActivityId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("HubstaffOrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("HubstaffUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HubstaffUserEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("HubstaffUserId")
                        .HasColumnType("int");

                    b.Property<int>("IdleSeconds")
                        .HasColumnType("int");

                    b.Property<int>("InputTrackedSeconds")
                        .HasColumnType("int");

                    b.Property<int>("ManualSeconds")
                        .HasColumnType("int");

                    b.Property<int>("OverallActiveSeconds")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("TrackedSeconds")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId", "WorkDate");

                    b.HasIndex("HubstaffOrganizationId", "HubstaffDailyActivityId")
                        .IsUnique();

                    b.HasIndex("HubstaffOrganizationId", "WorkDate");

                    b.HasIndex("HubstaffOrganizationId", "HubstaffUserId", "WorkDate");

                    b.ToTable("HubstaffDailyActivities", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.HubstaffOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedPersonalAccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HubstaffOrganizationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("LastSyncedToDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastValidatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastValidationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PatExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .IsUnique();

                    b.ToTable("HubstaffOrganizations", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.HubstaffSyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivitiesFetched")
                        .HasColumnType("int");

                    b.Property<int>("ActivitiesUpserted")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<int>("OrganizationCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.Property<bool>("TriggeredManually")
                        .HasColumnType("bit");

                    b.Property<int>("UnmappedUsersSkipped")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("HubstaffSyncRuns", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.KpiSyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeveloperCount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TasksUpserted")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.Property<bool>("TriggeredManually")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("KpiSyncRuns", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.LeaveApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicantDeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApproverDeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("RequestedDays")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewerComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("FromDate");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("ApplicantDeveloperId", "Status");

                    b.HasIndex("ApproverDeveloperId", "Status");

                    b.ToTable("LeaveApplications", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.LeaveSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EncryptedTelegramBotToken")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LastTelegramError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LastTelegramSuccessAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeekendDaysBitmask")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LeaveSettings", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.LeaveType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountingMode")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysPerYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PolicyNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("LeaveTypes", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.SyncedTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("CompletionDays")
                        .HasColumnType("float");

                    b.Property<long?>("DateCreated")
                        .HasColumnType("bigint");

                    b.Property<long?>("DateDone")
                        .HasColumnType("bigint");

                    b.Property<long?>("DueDate")
                        .HasColumnType("bigint");

                    b.Property<string>("FolderName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubtask")
                        .HasColumnType("bit");

                    b.Property<string>("ListName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParentTaskId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ParentTaskName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "TaskId")
                        .IsUnique();

                    b.HasIndex("AccountId", "IsCompleted", "DateCreated");

                    b.HasIndex("AccountId", "IsCompleted", "DateDone");

                    b.ToTable("SyncedTasks", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.TaskAssignmentPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UnassignedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "TaskId", "DeveloperId")
                        .IsUnique()
                        .HasDatabaseName("IX_TaskAssignmentPeriods_Open")
                        .HasFilter("[UnassignedAtUtc] IS NULL");

                    b.HasIndex("DeveloperId", "AssignedAtUtc", "UnassignedAtUtc");

                    b.HasIndex("AccountId", "TaskId", "DeveloperId", "UnassignedAtUtc");

                    b.ToTable("TaskAssignmentPeriods", (string)null);
                });

            modelBuilder.Entity("DevPulse.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId")
                        .IsUnique()
                        .HasFilter("[DeveloperId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.AttendanceCorrectionRequest", b =>
                {
                    b.HasOne("DevPulse.Domain.Entities.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("DevPulse.Domain.Entities.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.Developer", b =>
                {
                    b.HasOne("DevPulse.Domain.Entities.Developer", "ReportingManager")
                        .WithMany()
                        .HasForeignKey("ReportingManagerDeveloperId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ReportingManager");
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.DeveloperClickUpMapping", b =>
                {
                    b.HasOne("DevPulse.Domain.Entities.ClickUpAccount", "ClickUpAccount")
                        .WithMany()
                        .HasForeignKey("ClickUpAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevPulse.Domain.Entities.Developer", "Developer")
                        .WithMany("ClickUpMappings")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClickUpAccount");

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.DeveloperHubstaffMapping", b =>
                {
                    b.HasOne("DevPulse.Domain.Entities.Developer", "Developer")
                        .WithMany("HubstaffMappings")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevPulse.Domain.Entities.HubstaffOrganization", "HubstaffOrganization")
                        .WithMany("Mappings")
                        .HasForeignKey("HubstaffOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("HubstaffOrganization");
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.DeveloperKpiSnapshot", b =>
                {
                    b.HasOne("DevPulse.Domain.Entities.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevPulse.Domain.Entities.KpiSyncRun", "SyncRun")
                        .WithMany()
                        .HasForeignKey("SyncRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("SyncRun");
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.HubstaffDailyActivity", b =>
                {
                    b.HasOne("DevPulse.Domain.Entities.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevPulse.Domain.Entities.HubstaffOrganization", "HubstaffOrganization")
                        .WithMany("DailyActivities")
                        .HasForeignKey("HubstaffOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("HubstaffOrganization");
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.LeaveApplication", b =>
                {
                    b.HasOne("DevPulse.Domain.Entities.Developer", "ApplicantDeveloper")
                        .WithMany()
                        .HasForeignKey("ApplicantDeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevPulse.Domain.Entities.Developer", "ApproverDeveloper")
                        .WithMany()
                        .HasForeignKey("ApproverDeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevPulse.Domain.Entities.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicantDeveloper");

                    b.Navigation("ApproverDeveloper");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.SyncedTask", b =>
                {
                    b.HasOne("DevPulse.Domain.Entities.ClickUpAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.TaskAssignmentPeriod", b =>
                {
                    b.HasOne("DevPulse.Domain.Entities.ClickUpAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevPulse.Domain.Entities.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("DevPulse.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.HasOne("DevPulse.Domain.Entities.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DevPulse.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DevPulse.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevPulse.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DevPulse.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.Developer", b =>
                {
                    b.Navigation("ClickUpMappings");

                    b.Navigation("HubstaffMappings");
                });

            modelBuilder.Entity("DevPulse.Domain.Entities.HubstaffOrganization", b =>
                {
                    b.Navigation("DailyActivities");

                    b.Navigation("Mappings");
                });
#pragma warning restore 612, 618
        }
    }
}
